-- This works like an index.ts that exports all the files from a module
require('georgian.telescope')
require('georgian.gitsigns')
require('georgian.treesitter')
require('georgian.cmp')
require('georgian.lsp')
require('georgian.autopairs')
require('georgian.comment')
require('georgian.nvim-tree')
require('georgian.bufferline')
